version: '3'

networks:
  LEMP:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: LEMP_nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www
      - ./confs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - LEMP

  mariadb:
    build: docker/mysql
    container_name: LEMP_mariaDB
    ports:
      - "3306:3306"
    depends_on:
      - nginx
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    networks:
      - LEMP
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
  php:
    build: docker/php
    container_name: LEMP_php
    volumes:
      - ./public:/var/www
      - ./confs/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "9000:9000"
    networks:
      - LEMP
