version: '3'

networks:
  LEMP:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: LEMP_nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www
      - ./confs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - LEMP

  mariadb:
    build: docker/mysql
    container_name: LEMP_mariaDB
    ports:
      - "3306:3306"
    depends_on:
      - nginx
    environment:
      - 'MYSQL_DATABASE=sss'
      - 'MYSQL_USER=sss'
      - 'MYSQL_PASSWORD=sss'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
    networks:
      - LEMP

  php:
    build: docker/php
    container_name: LEMP_php
    volumes:
      - ./public:/var/www
    ports:
      - "9000:9000"
    networks:
      - LEMP
